# Generated by Django 3.0.5 on 2020-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default=' ', max_length=20)),
                ('joblocation', models.CharField(max_length=20)),
                ('jobskills', models.CharField(max_length=50)),
                ('jobdescription', models.CharField(max_length=200)),
            ],
        ),
    ]
