# Generated by Django 3.0.5 on 2020-04-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_jobs_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_title',
            new_name='jobtitle',
        ),
    ]
