# Generated by Django 3.0.5 on 2020-04-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20200428_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('skills', models.CharField(default='', max_length=200)),
                ('experience', models.CharField(default='', max_length=300)),
                ('jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobs')),
            ],
        ),
    ]
