# Generated by Django 3.0.5 on 2020-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_remove_student_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='jobs',
            field=models.ManyToManyField(to='emp.jobs'),
        ),
    ]
