# Generated by Django 3.0.5 on 2020-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_auto_20200428_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_description',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
