# Generated by Django 3.0.5 on 2020-04-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_jobs_test_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
