# Generated by Django 3.0.5 on 2020-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_student_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='performance_score',
            field=models.FloatField(default=0.0),
        ),
    ]
