# Generated by Django 3.0.5 on 2020-04-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='jobs',
        ),
    ]
