# Generated by Django 3.0.5 on 2020-04-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_student_performance_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='test_score',
        ),
        migrations.AddField(
            model_name='jobs',
            name='criteria',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.TextField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobdescription',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobskills',
            field=models.TextField(max_length=50),
        ),
    ]
