# Generated by Django 3.0.5 on 2020-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_auto_20200430_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='emp_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
