# Generated by Django 3.0.5 on 2020-04-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0014_employer_emp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobcategory',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
