# Generated by Django 3.0.5 on 2020-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0016_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='jobs',
            field=models.ManyToManyField(null=True, to='emp.jobs'),
        ),
    ]
