# Generated by Django 3.0.5 on 2020-05-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0017_student_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='jobs',
        ),
        migrations.AddField(
            model_name='student',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobs'),
        ),
    ]
