# Generated by Django 3.0.5 on 2020-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0020_appliedjobs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='rel',
            field=models.ManyToManyField(null=True, to='emp.jobs'),
        ),
    ]
