# Generated by Django 3.0.5 on 2020-05-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0023_auto_20200501_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='user',
        ),
    ]
