# Generated by Django 3.0.5 on 2020-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0025_appliedjobs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appliedjobs',
            name='student',
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='student',
            field=models.ManyToManyField(to='emp.student'),
        ),
    ]
