# Generated by Django 3.0.5 on 2020-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0028_employer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
