# Generated by Django 3.0.5 on 2020-05-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0029_auto_20200501_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
