# Generated by Django 3.0.5 on 2020-05-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0032_auto_20200502_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
