# Generated by Django 3.0.5 on 2020-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0033_auto_20200502_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
