# Generated by Django 3.0.5 on 2020-05-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0034_student_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
