# Generated by Django 3.0.5 on 2020-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0035_student_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, default=' ', max_length=2000, null=True),
        ),
    ]
