# Generated by Django 3.0.5 on 2020-05-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0036_auto_20200505_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.TextField(default='', max_length=100),
        ),
    ]
