# Generated by Django 3.0.5 on 2020-05-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0037_auto_20200505_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
