# Generated by Django 3.0.5 on 2020-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0038_auto_20200505_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phno',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
