# Generated by Django 3.0.5 on 2020-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0039_auto_20200505_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phno',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
