# Generated by Django 3.0.5 on 2020-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0040_auto_20200505_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
