# Generated by Django 3.0.5 on 2020-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0044_auto_20200505_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=400),
        ),
    ]
