# Generated by Django 3.0.5 on 2020-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0045_student_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stream',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='performance_score',
        ),
        migrations.AddField(
            model_name='student',
            name='Lnk',
            field=models.URLField(blank=True, default=' ', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Spokentest_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.CharField(blank=True, default=0, max_length=1, null=True),
        ),
    ]
