# Generated by Django 3.0.5 on 2020-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0046_auto_20200505_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
