# Generated by Django 3.0.5 on 2020-05-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0047_student_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Lnk',
            new_name='Linkedin',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='document',
            new_name='upload_your_work',
        ),
    ]
