# Generated by Django 3.0.5 on 2020-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0048_auto_20200505_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
