# Generated by Django 3.0.5 on 2020-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0049_auto_20200505_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, default='pro1.png', null=True, upload_to=''),
        ),
    ]
