# Generated by Django 3.0.5 on 2020-05-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0050_employer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='emp.jobs'),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='student',
            field=models.ManyToManyField(blank=True, to='emp.student'),
        ),
    ]
