# Generated by Django 3.0.5 on 2020-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0053_appliedjobs_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='On Review', max_length=50, null=True),
        ),
    ]
