# Generated by Django 3.0.5 on 2020-05-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0054_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, default='On Review', max_length=50, null=True),
        ),
    ]
