# Generated by Django 3.0.5 on 2020-05-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0058_auto_20200509_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appliedjobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.appliedjobs'),
        ),
    ]
