# Generated by Django 3.0.5 on 2020-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0060_remove_notification_appliedjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.TextField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employer',
            name='emp_field',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
