# Generated by Django 3.0.5 on 2020-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0061_auto_20200511_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='criteria',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobdescription',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='joblocation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobskills',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobtitle',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
