# Generated by Django 3.0.5 on 2020-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0062_auto_20200511_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='review',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], max_length=200, null=True),
        ),
    ]
