# Generated by Django 3.0.5 on 2020-05-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0063_appliedjobs_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='review',
        ),
    ]
