# Generated by Django 3.0.5 on 2020-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0064_remove_appliedjobs_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=' ', max_length=50)),
                ('comment', models.CharField(default=' ', max_length=200)),
            ],
        ),
    ]
