# Generated by Django 3.0.5 on 2020-05-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0066_contact_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_stu',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.student'),
        ),
    ]
