# Generated by Django 3.0.5 on 2020-05-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0069_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(choices=[('bad', 1), ('average', 2), ('good', 3), ('very good', 4), ('excellent', 5)]),
        ),
    ]
