# Generated by Django 3.0.5 on 2020-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0070_auto_20200518_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
