# Generated by Django 3.0.5 on 2020-05-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0072_auto_20200518_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='status_student',
            field=models.CharField(blank=True, default='On Review', max_length=50, null=True),
        ),
    ]
