# Generated by Django 3.0.5 on 2020-05-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0073_appliedjobs_status_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='status_student',
        ),
        migrations.AddField(
            model_name='student',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobs'),
        ),
    ]
