# Generated by Django 3.0.5 on 2020-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0074_auto_20200518_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comp', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True)),
            ],
        ),
    ]
