# Generated by Django 3.0.5 on 2020-05-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0077_auto_20200518_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='jobs',
        ),
    ]
