# Generated by Django 3.0.5 on 2020-05-20 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0078_remove_student_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_status',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student_status',
            name='semail',
        ),
        migrations.RemoveField(
            model_name='student_status',
            name='sphno',
        ),
        migrations.AddField(
            model_name='student_status',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobs'),
        ),
        migrations.AddField(
            model_name='student_status',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.student'),
        ),
    ]
