# Generated by Django 3.0.5 on 2020-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0081_pay_payupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='name',
            field=models.CharField(default='', max_length=90),
        ),
    ]
