# Generated by Django 3.0.5 on 2020-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0082_pay_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='address',
            field=models.CharField(default='', max_length=111),
        ),
    ]
