# Generated by Django 3.0.5 on 2020-05-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0083_pay_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='name',
        ),
    ]
